apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: abraxas-dashboard
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: abraxas
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - abraxas-prod