"""Strict mapping of rune IDs to operator functions.

Auto-generated by abx_runes_build.py --strict-map
"""

from __future__ import annotations
from typing import Callable, Dict, Any

from .rfa import apply_rfa
from .tam import apply_tam
from .wsss import apply_wsss
from .sds import apply_sds
from .ipl import apply_ipl
from .add import apply_add

RUNE_FUNCTIONS: Dict[str, Callable[..., Any]] = {
    "ϟ₁": apply_rfa,
    "ϟ₂": apply_tam,
    "ϟ₃": apply_wsss,
    "ϟ₄": apply_sds,
    "ϟ₅": apply_ipl,
    "ϟ₆": apply_add,
}
